src/Entity/Actor.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ActorRepository")
 */
class Actor
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Movie", inversedBy="actors", cascade={"persist"})
     * @ORM\JoinTable(
     *     name = "actor_movie",
     *     joinColumns={@ORM\JoinColumn(name="actor_id",referencedColumnName="id")},
     *     inverseJoinColumns={@ORM\JoinColumn(name="movie_id",referencedColumnName="id")}
     * )
     */
    private $movie;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $ActorName;

    /**
     * @ORM\Column(type="integer")
     */
    private $Age;

	/**
	 * @ORM\Column(type="string", length=255)
	 * @Assert\Image()
	 */
	private $Image;

    public function __construct()
    {
        $this->movie = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * @return Collection|Movie[]
     */
    public function getMovie(): Collection
    {
        return $this->movie;
    }

    public function addMovie(Movie $movie): self
    {
    	$this->movie[] = $movie;

        return $this;
    }

    public function removeMovie(Movie $movie): self
    {
        if ($this->movie->contains($movie)) {
            $this->movie->removeElement($movie);
        }

        return $this;
    }

    public function getActorName(): ?string
    {
        return $this->ActorName;
    }

    public function setActorName(string $ActorName): self
    {
        $this->ActorName = $ActorName;

        return $this;
    }

    public function getAge(): ?int
    {
        return $this->Age;
    }

    public function setAge(int $Age): self
    {
        $this->Age = $Age;

        return $this;
    }

	public function getImage()
	{
		return $this->Image;
	}

	public function setImage($Image)
	{
		$this->Image = $Image;

		return $this;
	}
}

src/Entity/Movie.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Filesystem\Filesystem;
use Symfony\Component\HttpFoundation\File\Exception\FileException;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\MovieRepository")
 */
class Movie
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $MovieName;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $Director;

    /**
     * @ORM\Column(type="integer")
     */
    private $ReleaseYear;

	/**
	 * @ORM\Column(type="string", length=255)
	 * @Assert\Image()
	 */
	private $Image;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Actor", mappedBy="movie")
     */
    private $actors;

    public function __construct()
    {
        $this->actors = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getMovieName(): ?string
    {
        return $this->MovieName;
    }

    public function setMovieName(string $MovieName): self
    {
        $this->MovieName = $MovieName;

        return $this;
    }

    public function getDirector(): ?string
    {
        return $this->Director;
    }

    public function setDirector(string $Director): self
    {
        $this->Director = $Director;

        return $this;
    }

	public function getImage()
	{
		return $this->Image;
	}

	public function getImageFile()
	{
    	$file = new File();

	}

	public function setImage($Image)
	{
		$this->Image = $Image;

		return $this;
	}

    public function getReleaseYear(): ?int
    {
        return $this->ReleaseYear;
    }

    public function setReleaseYear(int $ReleaseYear): self
    {
        $this->ReleaseYear = $ReleaseYear;

        return $this;
    }

    /**
     * @return Collection|Actor[]
     */
    public function getActors(): Collection
    {
        return $this->actors;
    }

    public function addActor(Actor $actor): self
    {
    	$this->actors[] = $actor;

        return $this;
    }

    public function removeActor(Actor $actor): self
    {
        if ($this->actors->contains($actor)) {
            $this->actors->removeElement($actor);
            $actor->removeMovie($this);
        }

        return $this;
    }
}

src/Controller/CinemaController.php
<?php
    namespace App\Controller;

    use App\Entity\Actor;
    use App\Entity\Movie;
    use Symfony\Bridge\Doctrine\Form\Type\EntityType;
    use Symfony\Component\Filesystem\Filesystem;
    use Symfony\Component\HttpFoundation\File\Exception\FileException;
    use Symfony\Component\HttpFoundation\File\UploadedFile;
    use Symfony\Component\HttpFoundation\Response;
    use Symfony\Component\Routing\Annotation\Route;
    use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
    use Symfony\Component\HttpFoundation\Request;
    use Symfony\Component\Form\Extension\Core\Type\TextType;
    use Symfony\Component\Form\Extension\Core\Type\TextareaType;
    use Symfony\Component\Form\Extension\Core\Type\SubmitType;
    use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
    use Symfony\Component\Form\Extension\Core\Type\FileType;

    class CinemaController extends AbstractController{

        /**
         * @Route("/",methods={"GET"}, name="index")
         */
        public function index(){

            return $this->render('cinemas/index.html.twig');
        }

	    /**
	     * @Route("/movie",methods={"GET"}, name="movie_list")
	     */
	    public function MovieList(){

		    $movies = $this->getDoctrine()->getRepository(Movie::class)->findAll();
		    return $this->render('cinemas/movielist.html.twig', array('movies' => $movies));
	    }

	    /**
	     * @Route("/actor",methods={"GET"}, name="actor_list")
	     */
	    public function ActorList(){

		    $actors = $this->getDoctrine()->getRepository(Actor::class)->findAll();
		    return $this->render('cinemas/actorlist.html.twig', array('actors' => $actors));
	    }

        /**
         * @Route("/movie/new", name="new_movie", methods={"GET", "POST"})
         */
        public function NewMovie(Request $request){
        	$movie = new Movie();
	        $actors = $this->getDoctrine()->getRepository(Actor::class)->findAll();

        	$form = $this->createFormBuilder($movie)
		        ->add('MovieName', TextType::class, array(
		        	'attr' => array('class' => 'form-control')))
		        ->add('Director', TextType::class, array(
		        	'attr' => array('class' => 'form-control')))
		        ->add('ReleaseYear', TextType::class, array(
			        'attr' => array('class' => 'form-control')))
		        ->add('Image', FileType::class, array(
			        'attr' => array('class' => 'form-control')))
		        ->add('actors', EntityType::class, array(
		        	'class' => Actor::class,
			        'choices' => $actors,
			        'choice_label' => 'ActorName',
			        'multiple' => true,
			        'required' => false
		        ))
		        ->add('Save', SubmitType::class, array(
		        	'label' => 'Create',
			        'attr' => array('class' => 'btn btn-primary m-3')))
		        ->getForm();

        	$form->handleRequest($request);

        	if ($form->isSubmitted() && $form->isValid())
	        {
	        	$movie = $form->getData();

		        /**
		         * @var UploadedFile $file
		         */
		        $file = $form->get('Image')->getData();
		        $fileName = md5(uniqid()).'.'.$file->guessExtension();

		        try {
			        $file->move('images', $fileName);
		        }catch (FileException $e)
		        {
		        	echo $e->getMessage();
		        }
		        foreach ($movie->getActors() as $actor)
		        {
			        $movie->addActor($actor);
			        $actor->addMovie($movie);
		        }

		        $movie->setImage($fileName);
	        	$entityManager = $this->getDoctrine()->getManager();
	        	$entityManager->persist($movie);
	        	$entityManager->flush();

		        return $this->redirectToRoute('movie_list');
	        }

			return $this->render('cinemas/newmovie.html.twig', array(
				'form' => $form->createView()));
        }

	    /**
	     * @Route("/movie/edit/{id}", name="edit_movie", methods={"GET", "POST"})
	     */
	    public function EditMovie(Request $request, $id){
		    $movie = new Movie();
		    $movie = $this->getDoctrine()->getRepository(
			    Movie::class)->find($id);

		    $imageFileName = $movie->getImage();

		    $actors = $this->getDoctrine()->getRepository(Actor::class)->findAll();

		    $form = $this->createFormBuilder($movie)
			    ->add('MovieName', TextType::class, array(
				    'attr' => array('class' => 'form-control')))
			    ->add('Director', TextType::class, array(
				    'attr' => array('class' => 'form-control')))
			    ->add('ReleaseYear', TextType::class, array(
				    'attr' => array('class' => 'form-control')))
			    ->add('Image', FileType::class, array(
				    'attr' => array('class' => 'form-control'),
				    'data_class' => null,
				    'required' => false))
			    ->add('Save', SubmitType::class, array(
				    'label' => 'Update',
				    'attr' => array('class' => 'btn btn-primary m-3')))
			    ->getForm();

		    $form->handleRequest($request);

		    if ($form->isSubmitted() && $form->isValid())
		    {
			    $file = $form->get('Image')->getData();

			    if ($file === null)
			    {
			    	$movie->setImage($imageFileName);
			    }
			    else
			    {
				    $file = $form->get('Image')->getData();
				    $fileName = md5(uniqid()).'.'.$file->guessExtension();

				    try {
					    $file->move('images', $fileName);
				    }catch (FileException $e)
				    {
					    echo $e->getMessage();
				    }

				    $movie->setImage($fileName);
			    }

			    $entityManager = $this->getDoctrine()->getManager();
			    $entityManager->flush();

			    return $this->redirectToRoute('movie_list');
		    }

		    return $this->render('cinemas/editmovie.html.twig', array(
			    'form' => $form->createView()));
	    }

	    /**
	     * @Route("/actor/new", name="new_actor", methods={"GET", "POST"})
	     */
	    public function NewActor(Request $requestActor){
		    $actor = new Actor();
		    $movies = $this->getDoctrine()->getRepository(Movie::class)->findAll();

		    $formActor = $this->createFormBuilder($actor)
			    ->add('ActorName', TextType::class, array(
				    'attr' => array('class' => 'form-control')))
			    ->add('Age', TextType::class, array(
				    'attr' => array('class' => 'form-control')))
			    ->add('Image', FileType::class, array(
				    'attr' => array('class' => 'form-control')))
			    ->add('movie', EntityType::class, array(
				    'class' => Movie::class,
				    'choices' => $movies,
				    'choice_label' => 'MovieName',
				    'multiple' => true
			    ))
			    ->add('Save', SubmitType::class, array(
				    'label' => 'Create',
				    'attr' => array('class' => 'btn btn-primary m-3')))
			    ->getForm();

		    $formActor->handleRequest($requestActor);

		    if ($formActor->isSubmitted() && $formActor->isValid())
		    {
			    $actor = $formActor->getData();

			    /**
			     * @var UploadedFile $file
			     */
			    $file = $formActor->get('Image')->getData();
			    $fileName = md5(uniqid()).'.'.$file->guessExtension();

			    try {
				    $file->move('images', $fileName);
			    }catch (FileException $e)
			    {
				    echo $e->getMessage();
			    }

			    foreach ($actor->getMovie() as $movie)
			    {
				    $movie->addActor($actor);
			    }

			    $actor->setImage($fileName);
			    $entityManager = $this->getDoctrine()->getManager();
			    $entityManager->persist($actor);
			    $entityManager->flush();

			    return $this->redirectToRoute('actor_list');
		    }

		    return $this->render('cinemas/newactor.html.twig', array(
			    'form' => $formActor->createView()));
	    }

	    /**
	     * @Route("/actor/edit/{id}", name="edit_actor", methods={"GET", "POST"})
	     */
	    public function EditActor(Request $requestActor, $id){
		    $actor = new Actor();
		    $actor = $this->getDoctrine()->getRepository(
			    Actor::class)->find($id);

		    $imageFileName = $actor->getImage();

		    $formActor = $this->createFormBuilder($actor)
			    ->add('ActorName', TextType::class, array(
				    'attr' => array('class' => 'form-control')))
			    ->add('Age', TextType::class, array(
				    'attr' => array('class' => 'form-control')))
			    ->add('Image', FileType::class, array(
				    'attr' => array('class' => 'form-control'),
				    'data_class' => null,
				    'required' => false))
			    ->add('Save', SubmitType::class, array(
				    'label' => 'Update',
				    'attr' => array('class' => 'btn btn-primary m-3')))
			    ->getForm();

		    $formActor->handleRequest($requestActor);

		    if ($formActor->isSubmitted() && $formActor->isValid())
		    {
			    $file = $formActor->get('Image')->getData();

			    if ($file === null)
			    {
				    $actor->setImage($imageFileName);
			    }
			    else
			    {
				    $file = $formActor->get('Image')->getData();
				    $fileName = md5(uniqid()).'.'.$file->guessExtension();

				    try {
					    $file->move('images', $fileName);
				    }catch (FileException $e)
				    {
					    echo $e->getMessage();
				    }

				    $actor->setImage($fileName);
			    }

			    $entityManager = $this->getDoctrine()->getManager();
			    $entityManager->flush();

			    return $this->redirectToRoute('actor_list');
		    }

		    return $this->render('cinemas/editactor.html.twig', array(
			    'form' => $formActor->createView()));
	    }

	    /**
	     * @Route("/movie/{id}", methods={"GET"}, name="movie_show")
	     */
	    public function ShowMovie($id){
		    $movie = $this->getDoctrine()->getRepository(
			    Movie::class)->find($id);
		    return $this->render('cinemas/showmovie.html.twig',
			    array('movie' => $movie));
	    }

	    /**
	     * @Route("/movie/delete/{id}", methods={"GET","DELETE"})
	     * @return Response
	     */
	    public function DeleteMovie(Request $request, $id)
	    {
		    $movie = $this->getDoctrine()->getRepository(
			    Movie::class)->find($id);


		    foreach ($movie->getActors() as $actor){
		    	$movie->removeActor($actor);
		    }

templates/cinemas/actorlist.html.twig
{% extends 'base.html.twig' %}

{% block title %}Cinema Application{% endblock %}

{% block body %}
    {% if actors %}
        <table id="actors" class="table table-striped">
            <thead>
            <tr>
                <th>Actor Name</th>
                <th>Actor Age</th>
                <th>Actions</th>
            </tr>
            </thead>
            <tbody>
            {% for actor in actors %}
                <tr>
                    <td>{{ actor.actorName }}</td>
                    <td>{{ actor.age }}</td>
                    <td>
                        <a href="/actor/{{ actor.id }}" class="btn btn-dark">Show</a>
                        <a href="/actor/edit/{{ actor.id }}" class="btn btn-light">Edit</a>
                        <a href="/actor/delete/{{ actor.id }}" class="btn btn-danger delete-actor" data-id="{{ actor.id }}">Delete</a>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    {% else %}
        <p>No Actors to display</p>
    {% endif %}
{% endblock %}
{% block javascripts %}
    <script src="{{ asset('js/main.js') }}"></script>
{% endblock %}

templates/cinemas/editactor.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Actor{% endblock %}

{% block body %}
    {{ form_start(form) }}
    {{ form_widget(form) }}
    {{ form_end(form) }}
{% endblock %}

templates/cinemas/editmovie.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Movie{% endblock %}

{% block body %}
    {{ form_start(form) }}
    {{ form_widget(form) }}
    {{ form_end(form) }}
{% endblock %}

templates/cinemas/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Cinema Application{% endblock %}

{% block body %}
    <div align="center"><h1>This is Cinema Application</h1></div>
{% endblock %}

templates/cinemas/movielist.html.twig
{% extends 'base.html.twig' %}

{% block title %}Cinema Application{% endblock %}

{% block body %}
    {% if movies %}
        <table id="movies" class="table table-striped">
            <thead>
            <tr>
                <th>Movie Name</th>
                <th>Actions</th>
            </tr>
            </thead>
            <tbody>
            {% for movie in movies %}
                <tr>
                    <td>{{ movie.movieName }}</td>
                    <td>
                        <a href="/movie/{{ movie.id }}" class="btn btn-dark">Show</a>
                        <a href="/movie/edit/{{ movie.id }}" class="btn btn-light">Edit</a>
                        <a href="/movie/delete/{{ movie.id }}" class="btn btn-danger delete-movie" data-id="{{ movie.id }}">Delete</a>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    {% else %}
        <p>No Movies to display</p>
    {% endif %}
{% endblock %}
{% block javascripts %}
    <script src="{{ asset('js/main.js') }}"></script>
{% endblock %}

templates/cinemas/newactor.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Actor{% endblock %}

{% block body %}
    {{ form_start(form) }}
    {{ form_widget(form) }}
    {{ form_end(form) }}
{% endblock %}

templates/cinemas/newmovie.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Movie{% endblock %}

{% block body %}
    {{ form_start(form) }}
    {{ form_widget(form) }}
    {{ form_end(form) }}
{% endblock %}

templates/cinemas/showactor.html.twig
{% extends 'base.html.twig' %}

{% block title %}Cinema Application{% endblock %}

{% block body %}
    <h1>{{ actor.actorName }}&nbsp;({{ actor.age }})</h1>
    <hr>
    <img src="/images/{{ actor.image }}", alt="Örnek Resim"
         width="200" height="200"
    />
    <hr>
    <div align="center"><h1>Filmleri</h1></div>
    <hr>
    <table class="table table-striped">
        <thead>
        <tr>
            <th>Movie Name</th>
            <th>Director</th>
            <th>Release Year</th>
        </tr>
        </thead>
        <tbody>
        {% for movie in actor.getMovie() %}
            <tr>
                <td>{{ movie.movieName }}</td>
                <td>{{ movie.Director }}</td>
                <td>{{ movie.ReleaseYear }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="/actor">Go Back</a>
{% endblock %}

templates/cinemas/showmovie.html.twig
{% extends 'base.html.twig' %}

{% block title %}Cinema Application{% endblock %}

{% block body %}
    <h1>{{ movie.movieName }}&nbsp;({{ movie.releaseYear }})</h1>
    <hr>
    <img src="/images/{{ movie.image }}", alt="Örnek Resim"
        width="200" height="200"
    />
    <hr>
    <div align="center"><h1>Oyuncular</h1></div>
    <hr>
    <table class="table table-striped">
        <thead>
        <tr>
            <th>Actor Name</th>
            <th>Actor Age</th>
        </tr>
        </thead>
        <tbody>
        {% for actor in movie.getActors() %}
            <tr>
                <td>{{ actor.actorName }}</td>
                <td>{{ actor.age }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    <a href="/movie">Go Back</a>
{% endblock %}